build-job:
  stage: build
  script:
    - python3 -m pip install .

test-scripting:
  stage: test
  script:
    - gboml test/test28.txt --linprog

test-graph:
  stage: test
  script:
    - python3
    - import gboml
    - exit()
