image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

build-job:
  stage: build
  script:
    - python3 -m pip install .

test-scripting:
  stage: test
  script:
    - gboml test/test28.txt --linprog

test-graph:
  stage: test
  script:
    - python3
    - import gboml
    - exit()
