%import common.ESCAPED_STRING -> STRING
%import common.INT -> INT
%import common.FLOAT -> FLOAT
%import common.CNAME -> ID
%import common.WS
%import common.CPP_COMMENT -> SINGLE_LINE_COMMENT
%import common.C_COMMENT -> MULTI_LINE_COMMENT
%ignore WS
%ignore SINGLE_LINE_COMMENT
%ignore MULTI_LINE_COMMENT

//MACROS
_separated_list{sub, sep}: sub (sep sub)*
separated_list{sub, sep}: _separated_list{sub, sep}
_separated_maybe_empty_list{sub, sep}: _separated_list{sub, sep}?
separated_maybe_empty_list{sub, sep}: _separated_list{sub, sep}?
olist{content}: content* //optionnal list
mlist{content}: content+ //mandatory list
_block_repeat_or_pass{name, content}: name (_PASS ";" | content+)
_block_shortcut{name, content}: name (_PASS? ";" | content)
_PASS.1: "pass"

// HEADER
start: [time_horizon] global_block program_block
program_block: _program*
?time_horizon: "#TIMEHORIZON" "T" "=" expression ";"
global_block: _block_repeat_or_pass{"#GLOBAL",definition}?
_program: node | hyperedge

// TAGS
tags: TAG*
TAG: /@[a-zA-Z\-_]+/

// Extends
extends: "extends" _path ["from" STRING]

// NODES
?node: node_definition | node_definition_gen | node_import
node_definition: _block_shortcut{_node_header, _node_content}
node_definition_gen: _block_shortcut{_node_header_gen, _node_content}
_node_header: "#NODE" ID [extends] tags
_node_header_gen: "#NODE" ID mlist{index_id} [extends] loop tags
_node_content: parameters_block program_block variables_block constraints_block objectives_block

parameters_block: (_block_repeat_or_pass{_opt_param_header,definition})?
_opt_param_header: "#PARAMETERS"?
variables_block: _block_repeat_or_pass{"#VARIABLES",variable_definition}
constraints_block: (_block_repeat_or_pass{"#CONSTRAINTS",_constraint_block_c})?
_constraint_block_c: constraint | ctr_activate | ctr_deactivate
objectives_block: (_block_repeat_or_pass{"#OBJECTIVES",_objective_block_c})?
_objective_block_c: objective | obj_activate | obj_deactivate

node_import: "#NODE" ID "=" "import" _path "from" STRING node_redefs
node_redefs: ("with" redefinition*) | ";"
?redefinition: variable_scope_change | definition
variable_scope_change: ID SCOPE ";"

// HYPEREDGES
?hyperedge: hyperedge_definition | hyperedge_definition_gen | hyperedge_import

hyperedge_definition: _block_shortcut{_hyperedge_header, _hyperedge_content}
hyperedge_definition_gen: _block_shortcut{_hyperedge_header_gen, _hyperedge_content}
_hyperedge_header: "#HYPEREDGE" ID [extends] tags
_hyperedge_header_gen: "#HYPEREDGE" ID mlist{index_id} [extends] loop tags
_hyperedge_content: parameters_block constraints_block

hyperedge_import: "#HYPEREDGE" ID "=" "import" _path "from" STRING hyperedge_redefs
hyperedge_redefs: "with" definition* | ";"

// VARIABLES
variable_definition_std: SCOPE [VTYPE] ":" separated_list{variable_name,","} tags ";"
variable_definition_arrow: SCOPE [VTYPE] ":" separated_list{variable_name,","} "<-" separated_list{_path, ","} tags ";"
variable_definition_limit: SCOPE [VTYPE] ":" separated_list{variable_name,","} "in" "[" [expression] ":" [expression] "]" tags ";"
?variable_definition: variable_definition_arrow | variable_definition_limit | variable_definition_std
SCOPE: "internal" | "external"
VTYPE: "binary" | "continuous" | "integer"
variable_name: ID olist{index}

// CONSTRAINTS
constraint: [ID ":"] expression [loop] tags ";"

// OBJECTIVES
objective: OBJ_TYPE [ID] ":" expression [loop] tags ";"
OBJ_TYPE: "min" | "max"

// LOOPS
?loop: _true_loop | implicit_loop
_true_loop: base_loop | like_loop
base_loop: "for" ID "in" expression ["where" expression] [_true_loop]
like_loop: "for" ID "like" _path ["where" expression] [_true_loop] //_path must point to an indexing param
implicit_loop: "where" expression

// DEFINITIONS
?definition: definition_std_param | definition_indexing_param
definition_indexing_param: ID "in" expression ";"
definition_std_param: ID ["(" separated_list{ID, ","} ")"] DEF_TYPE expression_or_string tags ";"
DEF_TYPE: "=" | "<-"

// ARRAYS
array_or_dict: "{" separated_maybe_empty_list{_array_or_dict_entry, ","} "}"
array: "{" separated_maybe_empty_list{generated_expression, ","} "}"
dict: "{" separated_maybe_empty_list{dict_entry, ","} "}"
_array_or_dict_entry: generated_expression | dict_entry
dict_entry: expression_or_string ":" expression [loop]

// RANGE
range: "[" expression ":" expression [":" expression] "]"

// EXPRESSIONS
?expression_or_string: expression | STRING  // no operation is allowed on strings
?expression: bool_expression

?bool_expression: bool_expression_or
?bool_expression_or: _separated_list{bool_expression_and, "or"}
?bool_expression_and: _separated_list{_maybe_not, "and"}
_maybe_not: bool_expression_not | _bool_expression_leaf
bool_expression_not: "not" _bool_expression_leaf
_bool_expression_leaf: bool_expression_comparison | _other_expression
bool_expression_comparison: _other_expression COMPARISON_OPERATOR _other_expression
COMPARISON_OPERATOR:  "<" | ">" | "!=" | "<=" | ">=" | "=="

_other_expression: concatenation
?concatenation: _separated_list{subtraction, "|"}
?subtraction: _separated_list{sum, "-"}
?sum: _separated_list{division, "+"}
?division: _separated_list{product, "/"}
?product: _separated_list{modulo, "*"}
?modulo: _separated_list{_maybe_unary_minus, "%"}
_maybe_unary_minus: unary_minus | exponent
unary_minus: "-" exponent
?exponent: _separated_list{_maybe_call, "**"}
_maybe_call: _call | "(" expression ")" | _leaf_value
_call: function_call | dot_call | array_call | "(" _call ")"
function_call: (_call | _leaf_callable) "(" separated_list{generated_expression, ","} ")"
dot_call: (_call | _leaf_dotable) "." ID
array_call: (_call | _leaf_indexable) "[" expression_or_string "]"
_leaf_value: path_root | INT | FLOAT | range | array_or_dict | import | TAG
_leaf_negatable: path_root | INT | FLOAT
_leaf_indexable: path_root | range | array_or_dict | import
_leaf_callable: path_root
_leaf_dotable: path_root

// ACTIVATE/DEACTIVATE
_activate.1: "activate" separated_list{_activation_id, ","} ["if" expression] ";"
_deactivate.1: "deactivate" separated_list{_activation_id, ","} ["if" expression] ";"
_activation_id: ID | TAG
ctr_activate: _activate
ctr_deactivate: _deactivate
obj_activate: _activate
obj_deactivate: _deactivate

// PATH - always points to a variable/parameter/node name
_path: path_root | dot_call | array_call
path_root: ID

// INDEXES
?index: "[" expression_or_string "]"
?index_id: "[" ID "]"

// IMPORT (old way to import csvs)
import: "import" STRING

// GENERATED EXPRESSIONS
?generated_expression: expression_or_string loop?
